version: 2.1
orbs:
  autify-cli: autify/autify-cli@dev:<<pipeline.git.revision>>
  node: circleci/node@5
  orb-tools: circleci/orb-tools@11.1

filters: &filters
  tags:
    only: /.*/

executors:
  linux:
    machine:
      resource_class: "medium"
      image: ubuntu-2204:2024.11.1
  windows:
    machine:
      resource_class: "windows.medium"
      image: windows-server-2022-gui:current
  macos:
    macos:
      xcode: 14.0.0
    resource_class: 'macos.m1.medium.gen1'

jobs:
  # Create a job to test the commands of your orbs.
  # You may want to add additional validation steps to ensure the commands are working as expected.
  default-tests:
    parameters:
      os:
        type: executor
    executor: << parameters.os >>
    shell: bash
    steps:
      - autify-cli/install
      - run: autify --version | grep -v beta
      - run: echo token | autify web auth login
      - run: echo token | autify mobile auth login
      - run: autify connect client install

  specific-tests:
    parameters:
      os:
        type: executor
    executor: << parameters.os >>
    shell: bash
    steps:
      - autify-cli/install:
          shell-installer-url: "https://autify-cli-assets.s3.amazonaws.com/autify-cli/channels/beta/install-cicd.bash"
      - run: autify --version | grep beta
      - run: echo token | autify web auth login
      - run: echo token | autify mobile auth login
      - run: autify connect client install

  integration-tests:
    parameters:
      os:
        type: executor
      shell-installer-url:
        type: string
      node-version:
        type: string
    executor: << parameters.os >>
    shell: bash
    environment:
      AUTIFY_CLI_INTEGRATION_TEST_INSTALL: 1
      AUTIFY_CONNECT_CLIENT_MODE: fake
    steps:
      - node/install:
          node-version: << parameters.node-version >>
      - run: nvm use << parameters.node-version >>
      - autify-cli/install:
          shell-installer-url: << parameters.shell-installer-url >>
      - run: echo token | autify web auth login
      - run: echo token | autify mobile auth login
      - run: autify connect client install
      - run: autify-cli-integration-test

workflows:
  test-deploy:
    when:
      not:
        equal: [scheduled_pipeline, << pipeline.trigger_source >>]
    jobs:
      # Make sure to include "filters: *filters" in every test job you want to run as part of your deployment.
      - default-tests:
          filters: *filters
          matrix:
            parameters:
              os: [linux, macos, windows]
      - specific-tests:
          filters: *filters
          matrix:
            parameters:
              os: [linux, macos, windows]
      - integration-tests:
          filters: *filters
          matrix:
            parameters:
              os: [linux, macos, windows]
          shell-installer-url: https://autify-cli-assets.s3.amazonaws.com/autify-cli/channels/stable/install-cicd.bash
          node-version: 18.14.2
      - orb-tools/pack:
          filters: *filters
      - orb-tools/publish:
          orb-name: autify/autify-cli
          vcs-type: << pipeline.project.type >>
          pub-type: production
          requires:
            - default-tests
            - specific-tests
            - integration-tests
            - orb-tools/pack
          context: orb-publishing
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/
  nightly-test:
    when:
      equal: [scheduled_pipeline, << pipeline.trigger_source >>]
    jobs:
      - integration-tests:
          name: stable-<< matrix.os >>
          matrix:
            parameters:
              os: [linux, macos, windows]
          shell-installer-url: https://autify-cli-assets.s3.amazonaws.com/autify-cli/channels/stable/install-cicd.bash
          node-version: 18.14.2
  nightly-beta-test:
    when:
      equal: [scheduled_pipeline, << pipeline.trigger_source >>]
    jobs:
      - integration-tests:
          name: beta-<< matrix.os >>
          matrix:
            parameters:
              os: [linux, macos, windows]
          shell-installer-url: https://autify-cli-assets.s3.amazonaws.com/autify-cli/channels/beta/install-cicd.bash
          node-version: 18.14.2
